import type { CollectionKey, EweDocument, ServerRoom } from '@eweser/shared';
import type { YSweetProvider } from '@y-sweet/client';
import type { IndexeddbPersistence } from 'y-indexeddb';
import { WebrtcProvider } from 'y-webrtc';
import type { RoomEvents } from './events';
import { TypedEventEmitter } from './events';
import type { Database, YDoc } from '.';
import type { GetDocuments } from './utils/getDocuments';
import { Doc } from 'yjs';
export type NewRoomOptions<T extends EweDocument> = {
    db: Database;
    id?: string;
    name: string;
    collectionKey: CollectionKey;
    token?: string | null;
    tokenExpiry?: string | null;
    ySweetUrl?: string | null;
    publicAccess?: 'private' | 'read' | 'write';
    readAccess?: string[];
    writeAccess?: string[];
    adminAccess?: string[];
    createdAt?: string | null;
    updatedAt?: string | null;
    _deleted?: boolean | null;
    _ttl?: string | null;
    indexedDbProvider?: IndexeddbPersistence | null;
    webRtcProvider?: WebrtcProvider | null;
    ySweetProvider?: YSweetProvider | null;
    ydoc?: YDoc<T> | null;
};
export declare class Room<T extends EweDocument> extends TypedEventEmitter<RoomEvents<T>> implements ServerRoom {
    db: Database;
    id: string;
    name: string;
    collectionKey: CollectionKey;
    token: string | null;
    tokenExpiry: string | null;
    ySweetUrl: string | null;
    publicAccess: 'private' | 'read' | 'write';
    readAccess: string[];
    writeAccess: string[];
    adminAccess: string[];
    createdAt: string | null;
    updatedAt: string | null;
    _deleted: boolean | null;
    _ttl: string | null;
    indexedDbProvider?: IndexeddbPersistence | null;
    webRtcProvider?: WebrtcProvider | null;
    ySweetProvider?: YSweetProvider | null;
    ydoc?: YDoc<T> | null;
    connectionRetries: number;
    disconnect: () => void;
    getDocuments: () => GetDocuments<T>;
    tempDoc: (docId: string) => {
        doc: Doc;
        provider?: WebrtcProvider | undefined;
        awareness?: any;
    };
    constructor({ db, indexedDbProvider, webRtcProvider, ySweetProvider, ydoc, ...serverRoom }: NewRoomOptions<T>);
}
export declare function roomToServerRoom(room: Room<any>): ServerRoom;
