server {
  listen ${PORT};
  server_name _;

  root /usr/share/nginx/html;

  port_in_redirect off;

  location = /health {
    return 200 'OK';
    add_header Content-Type text/plain;
  }

  location = / {
    return 302 https://$host/auth/;
  }

  location /auth/ {
    try_files $uri $uri/ /auth/index.html;
  }
}