[build]
dockerfilePath = "packages/auth-pages/Dockerfile"
buildCommand = ""

[deploy]
startCommand = "nginx -g 'daemon off;'"
healthcheckPath = "/"
healthcheckTimeout = 30
restartPolicyMaxRetries = 3
