import type { AgentConfig, AgentAccessLogEntry } from './agent-config.js';
import type { Note } from './note.js';
import type { Flashcard } from './flashcard.js';
import type { Profile } from './profile.js';
import type { DocumentBase } from './documentBase.js';
import type { Conversation } from './conversation.js';
export * from './note.js';
export * from './flashcard.js';
export * from './profile.js';
export * from './documentBase.js';
export * from './agent-config.js';
export * from './conversation.js';
export * from './folder.js';
/** We don't include registry because we use this after login to get all non-registry collections. */
export declare const COLLECTION_KEYS: readonly ["notes", "flashcards", "profiles", "agentConfigs", "agentAccessLogs", "conversations"];
export declare const COLLECTION_KEYS_OR_ALL: readonly ["notes", "flashcards", "profiles", "agentConfigs", "agentAccessLogs", "conversations", "all"];
export declare const PUBLIC_ACCESS_TYPES: readonly ["private", "read", "write"];
export type PublicAccessType = (typeof PUBLIC_ACCESS_TYPES)[number];
export declare const ROOM_ACCESS_TYPES: readonly ["read", "write", "admin"];
export type RoomAccessType = (typeof ROOM_ACCESS_TYPES)[number];
export declare const collectionKeys: ("notes" | "flashcards" | "profiles" | "agentConfigs" | "agentAccessLogs" | "conversations")[];
export type EweDocument = Note | Flashcard | Profile | AgentConfig | AgentAccessLogEntry | Conversation;
export type CollectionKey = (typeof COLLECTION_KEYS)[number];
export type CollectionKeyOrAll = (typeof COLLECTION_KEYS_OR_ALL)[number];
export type DocumentWithoutBase<T extends EweDocument> = Omit<T, keyof DocumentBase>;
