server {
  listen ${PORT};
  server_name _;

  root /usr/share/nginx/html;

  port_in_redirect off;

  location = /health {
    return 200 'OK';
    add_header Content-Type text/plain;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
