[build]
dockerfilePath = "packages/ewe-note/Dockerfile"
buildCommand = ""

[deploy]
startCommand = "nginx -g 'daemon off;'"
healthcheckPath = "/"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
