const SUPABASE_CONNECTION_URL = process.env.SUPABASE_CONNECTION_URL ?? '';

if (!SUPABASE_CONNECTION_URL) {
  throw new Error('SUPABASE_CONNECTION_URL not set');
}

const SUPABASE_SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY ?? '';

if (!SUPABASE_SERVICE_ROLE_KEY) {
  throw new Error('SUPABASE_SERVICE_ROLE_KEY not set');
}

export { SUPABASE_CONNECTION_URL, SUPABASE_SERVICE_ROLE_KEY };
